### ISSUE TITLE
The change in default for the three flag causes trouble

### ISSUE THREAD

**Issue by acowley** [ekmett/transformers-compat#10]
I discovered that that if I have a constraint on `transformers-compat ==0.4.0.4` and `mtl ==2.1.3.1`, `cabal install --dependencies-only --dry-run` in a sandbox won't work with GHC 7.8.4. Without the `transformers-compat` constraint, 0.4.0.3 with the `three` flag is picked, and everything is fine. Without the `mtl` constraint, `mtl-2.2.1` is picked, `transformers-0.4.3.0` is selected, and everything is fine. 

This is with `transformers-0.3.0.0` in the global package database, as is shipped with GHC 7.8.4, and `cabal-install-1.20.0.6`. I do not know how specifically to fix this, as I don't think the flag selection mechanism actually works properly, but is the change to the default status strictly necessary? I presume it was done for GHC 7.10.1.

**Comment by juhp** [comment]
Right - I /think/ "Manual: True" forces the flags to be static which is probably not desired?

**Comment by hvr** [comment]
There's maybe a misconception about how the purpose of these flags. Their purpose is to be able to almost use the same .cabal file for 0.4.0.2, 0.4.0.3 and 0.4.0.4 which differ only in their flag settings.

This could have been done competely without any flags at all. The end result is that:

 - `transformers-compat-0.4.0.2` needs `mtl==2.0.*` and `transformers==0.2.*`
 - `transformers-compat-0.4.0.3` needs `mtl==2.1.*` and `transformers==0.3.*`
 - `transformers-compat-0.4.0.4` needs `transformers==0.4.*`

So you're supposed to pick the respective version of `transformers-compat` that matches your `transformers`/`mtl` versions!

**Comment by ekmett** [comment]
The purpose of these flags and having 3 versions on hackage is to hack around a bug in cabal.

This permits us to get cabal to pick the right version of the flag based on what version of transformers is in use.

Without it you hit a bug in the backtracker on older cabal versions.

**Comment by acowley** [comment]
The issue doesn't affect me anymore, so I'm going to close this. Presumably it's still a fragile bit of the universe, but hopefully few will tread there again.

**Comment by ekmett** [comment]
I'd classify this as 'still working as intended, but not as you expected'.

When we ship `transformers-compat` 0.5 I'll similarly have to release a 0.5.0.2, 0.5.0.3, 0.5.0.4, and 0.5.0.5 with the same shenanigans.

**Comment by juhp** [comment]
Which versions of cabal-install are affected?

**Comment by ekmett** [comment]
AFAIK everything up until something around 1.22. The fix was very very recent.
