### ISSUE TITLE
Support for transformers 0.5.x?

### ISSUE THREAD

**Issue by peti** [ekmett/transformers-compat#15]
I tried test-building a couple of packages with GHC  8.0.1-rc1. but my attempts were rather unsuccessful because that compiler ships `transformers` version 0.5.x, which this library doesn't seem to support yet.. It would be great to get a new release that remedies this issue!

**Comment by RyanGlScott** [comment]
See https://github.com/ekmett/transformers-compat/issues/11#issuecomment-171136257

**Comment by ekmett** [comment]
Fixed in HEAD. Moving to hackage momentarily.

**Comment by peti** [comment]
Thank you very much!
