### ISSUE TITLE
Missing entries in CHANGELOG.markdown

### ISSUE THREAD

**Issue by asr** [ekmett/transformers-compat#16]
There are some missing entries in [CHANGELOG.markdown](http://hackage.haskell.org/package/transformers-compat-0.5.0.4/changelog).

**Comment by RyanGlScott** [comment]
I've gone through the `CHANGELOG.markdown` file and added an entry for every release in https://github.com/ekmett/transformers-compat/commit/f407d4d284b8a1ca6bfa33132a074e6ddc348c0e.

**Comment by asr** [comment]
Thanks!
