### ISSUE TITLE
Hackage release

### ISSUE THREAD

**Issue by andrewthad** [ekmett/transformers-compat#25]
I noticed that there's some pretty useful machinery in `Data.Functor.Classes.Generic`, but it hasn't been released to hackage. It would be nice to see this released.

**Comment by quasicomputational** [comment]
Ping? It really has been a while since the last release, and transformers has new stuff in it (Accum, primarily) that we're going to have to shim for a couple of GHC releases. It already looks like that's in HEAD, though, which is good.

**Comment by ocharles** [comment]
Another ping, would really like to use `AccumT`.

**Comment by RyanGlScott** [comment]
Apologies for the delay. I've uploaded the [`transformers-compat-0.6`](http://hackage.haskell.org/package/transformers-compat-0.6.0.6) series to Hackage.
