### ISSUE TITLE
transformers-compat-0.6.0.4 bounds

### ISSUE THREAD

**Issue by andrewthad** [ekmett/transformers-compat#35]
I get the following build error when I try to build `transformers-compat-0.6.0.4` with `ghc-7.10.3`:

```
[4 of 4] Compiling Control.Monad.Trans.Instances ( src/Control/Monad/Trans/Instances.hs, dist/build/Control/Monad/Trans/Instances.o )

src/Control/Monad/Trans/Instances.hs:352:41:
    Not in scope: `runIdentity'

src/Control/Monad/Trans/Instances.hs:503:24:
    Not in scope: `getReverse'

src/Control/Monad/Trans/Instances.hs:503:41:
    Not in scope: `getReverse'
```

**Comment by andrewthad** [comment]
Whoops. I reported the wrong version of `ghc` in the title of the issue. Try this:

    cabal new-build --constraint transformers==0.4.0.0 -w ghc-7.8.4

**Comment by RyanGlScott** [comment]
Ah, right. Now I see what is happening—you're using the `transformers-0.4.0.0` release, which included a very bold change to remove record syntax for many data types. That change was reverted in the next minor release, 0.4.1.0, and it seems to have never been reintroduced.

Personally, I wish that we could deprecate `transformers-0.4.0.0` entirely, as it was clearly a mistake to do this. But alas, it's not so we'll have to figure out how to deal with the damage.

My inclination is to just revise the version bounds to exclude `transformers-0.4.0.0` entirely from build plans. Would that work for you, or is the use of `transformers-0.4.0.0` critical?

**Comment by andrewthad** [comment]
Excluding it with the lower bound is fine. I don't actually need to build with that version in particular. I'm trying to make something compatible with `transformers-0.4.X` so that `primitive` can use it in the test suite. It looks like `primitive`'s travis setup uses something from the `transformers-0.4.X` versions that's newer than `0.4.0`.

**Comment by RyanGlScott** [comment]
Alright, I've revised the version bounds for `transformers` on Hackage accordingly. I'll opt to close this—do reopen if there's more that needs to be done here.
