### ISSUE TITLE
Accum/Select are not exposed when building against transformers-0.4.x

### ISSUE THREAD

**Issue by mvv** [ekmett/transformers-compat#37]
Got bitten by that on GHC 7.10 vs `--constraint="transformers installed"`. Fix is available in #36.

**Comment by mvv** [comment]
A new Hackage release would be appreciated.

**Comment by RyanGlScott** [comment]
I'm currently working on such a release.

**Comment by RyanGlScott** [comment]
I've uploaded the `transformers-compat-0.6.1` series to Hackage.

**Comment by mvv** [comment]
Thanks.
