### ISSUE TITLE
Compatibility with transformers 0.6

### ISSUE THREAD

**Issue by sjakobi** [ekmett/transformers-compat#48]
https://hackage.haskell.org/package/transformers-0.6.0.0/changelog

Could you upload a compatible release?

**Comment by RyanGlScott** [comment]
I'm currently working on this—see the work-in-progress [`transformers-0.6`](https://github.com/ekmett/transformers-compat/tree/transformers-0.6) branch. Making `transformers-compat` compatible with `transformers-0.6.*` isn't a simple matter of lifting version bounds, however, as code changes in the `0.6.*` series break some of the code in `transformers-compat`. It should be straightfoward to adapt to these changes, but it will take me some take to work out the right cocktail of CPP.

**Comment by RyanGlScott** [comment]
See #49.

**Comment by RyanGlScott** [comment]
I've uploaded [`transformers-compat-0.7`](https://hackage.haskell.org/package/transformers-compat-0.7) to Hackage, which supports `transformers-0.6.*`.
