### ISSUE TITLE
transformers-compat-0.3.3.4 incompatible with transformers-0.3.0.0 from latest HP

### ISSUE THREAD

**Issue by Blaisorblade** [ekmett/transformers-compat#5]
I'm working around ekmett/lens#458 by installing transformers-compat, but the latest version refuses to install, unless I manually provide `-f three`:
```
$ cabal install -v --dry-run --one-shot transformers-compat-0.3.3.4 -f three
Reading available packages...
Choosing modular solver.
Resolving dependencies...
In order, the following would be installed:
transformers-compat-0.3.3.4 +three (new version)
```

I've later found this is documented in 
https://github.com/ekmett/transformers-compat/commit/v0.3.3.4, but that seems a bit too little. Also, that's not the default behavior I get:
```
$ cabal install -v --dry-run --one-shot transformers-compat
Reading available packages...
Choosing modular solver.
Resolving dependencies...
In order, the following would be installed:
transformers-0.4.1.0 (new version)
transformers-compat-0.3.3.4 (new version)
```

```
$ cabal install -v --dry-run --one-shot transformers-compat-0.3.3.4 transformers-0.3.0.0
Reading available packages...
Choosing modular solver.
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: transformers-compat-0.3.3.4 (user goal)
next goal: transformers (user goal)
rejecting: transformers-0.4.1.0 (global constraint requires ==0.3.0.0)
rejecting: transformers-0.3.0.0/installed-ff2..., 0.3.0.0 (conflict:
transformers-compat-0.3.3.4:three => transformers>=0.4.1 && <0.5)
rejecting: transformers-0.2.2.1, 0.2.2.0, 0.2.1.0, 0.2.0.0, 0.1.4.0, 0.1.3.0,
0.1.1.0, 0.1.0.1, 0.1.0.0, 0.0.1.0, 0.0.0.0, 0.4.0.0 (global constraint
requires ==0.3.0.0)
Dependency tree exhaustively searched.
$ cabal install -v --dry-run --one-shot transformers-compat transformers-0.3.0.0
Reading available packages...
Choosing modular solver.
Resolving dependencies...
In order, the following would be installed:
transformers-compat-0.3.3.3 (latest: 0.3.3.4) (new version)
```

**Comment by pthariensflame** [comment]
Running into this problem with GHC 7.8.4 and the `transformers` installed as part of it.  Glad I found this thread, but it should probably be documented somewhere more prominent.

**Comment by Blaisorblade** [comment]
A relevant discussion might be the following one — if you still have this issue, please document the version of cabal-install you're using, since apparently transformers-compat runs into cabal *completeness* bugs when constructing the build plan (I'm confused whether the bugs only happen without --reorder-goals):
https://github.com/haskell/cabal/issues/1855#issuecomment-43503323
https://github.com/haskell/cabal/issues/1855#issuecomment-50594924

**Comment by RyanGlScott** [comment]
Indeed, this is simply a `cabal-install` issue. As https://github.com/haskell/cabal/issues/1855#issuecomment-50594924 notes, modern `cabal-install` (version 1.22 and up) shouldn't have this problem, and if you're using an older version, you should be using the 1.20.0.3 or 1.18.0.5 patch releases.

I don't know what `transformers-compat` can do about this, so I'll close this issue.
