### ISSUE TITLE
Should transformers-compat provide Eq1 Complex and (,,) (,,,) for GHC-7?

### ISSUE THREAD

**Issue by phadej** [ekmett/transformers-compat#50]
I.e. the same you recently added to `base-orphans` (thanks for that, that works perfectly).

It would allow me to keep next major of `hashable` buildable with older GHCs (for the relatively low price of needing to upgrade `transformers` on GHC-7.10 to avoid `transformers-0.4` `Eq1` variant).

EDIT: if `transformers-compat` would provide `Eq1` also for `transformers-0.4` variant, maybe I'll get away with it too.

Let me write a patch to test things out.

**Comment by RyanGlScott** [comment]
Yes, we probably should. The tricky part will be figuring out the correct CPP.
