### ISSUE TITLE
Make flag structure compatible with stack?

### ISSUE THREAD

**Issue by andreasabel** [ekmett/transformers-compat#52]
If I use `transformers-compat` as `extra-dep` in a `stack.yaml` file, I always need to provide the following magic incantation:
```
flags:
  transformers-compat:
    five-three: true
```
Can the flags be reorganized so that this isn't necessary?
It seems that `five-three` would be the choice nowadays in >99% of the cases.

**Comment by RyanGlScott** [comment]
How does `stack`'s flag selection work? Does it simply pick whatever the flags have `default: True` without doing any constraint solving? If so, I think changing `five-three`'s `default` would suffice to resolve this issue, but I'm unclear if there would be unforeseen consequences in `cabal-install`'s constraint solver.

**Comment by andreasabel** [comment]
> How does `stack`'s flag selection work? Does it simply pick whatever the flags have `default: True` without doing any constraint solving? 

I could not find anything about this in `stack`'s readthedocs.  But I think it does not backtrack, and what you suggest could be true.

> If so, I think changing `five-three`'s `default` would suffice to resolve this issue, but I'm unclear if there would be unforeseen consequences in `cabal-install`'s constraint solver.

Judging from the docs, it _should_ not have any adverse effects, see: https://cabal.readthedocs.io/en/latest/cabal-package.html?highlight=assignment#resolution-of-conditions-and-flags
Rather, it could speed up constraint solving by making the right pick from the start, should my conjecture about the >99% be correct.

**Comment by phadej** [comment]
`stack` doesn't have flag selection. It doesn't have solver, so all install plan information has to be provided manually.

Don't use `stack` if you wander outside of snapshots :)

**Comment by RyanGlScott** [comment]
I've applied a corresponding Hackage revision [here](https://hackage.haskell.org/package/transformers-compat-0.7.1/revisions/). I'll optimistically proceed under the assumption that the issue has been fixed, but if not, feel free to re-open the issue.
