### ISSUE TITLE
missing Control.Monad.Except

### ISSUE THREAD

**Issue by cartazio** [ekmett/transformers-compat#6]
should probably add it :)

**Comment by RyanGlScott** [comment]
I don't know if you're still having this issue, but I do have an [`mtl-compat`](http://hackage.haskell.org/package/mtl-compat) package which backports `Control.Monad.Except` (if you just want `mtl` instances for `ExceptT` though, `transformers-compat-0.4` now provides those).

**Comment by RyanGlScott** [comment]
I'm going to close this, since:

1. `mtl-compat` has a `Control.Monad.Except` module
2. `transformers-compat` now backports `mtl` instances
