### ISSUE TITLE
Provide Monad* instances from mtl for ExceptT

### ISSUE THREAD

**Issue by jcpetruzza** [ekmett/transformers-compat#7]
Since `mtl` depends directly on `transformers`, it is not possible afaics for a project already depending on `mtl` to switch to `ExceptT` and remain compatible with `transformers-0.3`. The cost of the proposal would be to introduce a dependency on `mtl`, but I don't see to be problematic in practice.

Alternatively, one could a) make `mtl` depend on `transformers-compat` or b) put the instances in a `mtl-compat` package. I think a) will probably not fly since it would introduce a dependency on a non-HP package while b) would be a much worse solution due to orphan instances.

**Comment by RyanGlScott** [comment]
I attempted to implement idea (b) in my [`mtl-compat`](http://hackage.haskell.org/package/mtl-compat-0.1) package. Does this suit your needs?

**Comment by RyanGlScott** [comment]
Never mind, `transformers-compat` now exports `mtl` instances, so this issue should be fixed without needing to use another package.

**Comment by RyanGlScott** [comment]
This has been fixed as of `transformers-compat-0.4`.
